export default [
  {
    banishable: true,
    cost: 4,
    factions: ['void'],
    honor: 1,
    id: 'arbiter_of_the_precipice',
    quote: `"Memory and history are no concern of mine. This foul thing should have never existed. Now it will be as if it never did."`,
    set: 'CotG',
    text: 'Draw two cards. Banish a card in your hand.',
    title: 'Arbiter of the Precipice',
    type: 'hero'
  },
  {
    banishable: true,
    cost: 1,
    factions: ['enlightened'],
    honor: 1,
    id: 'arha_initiate',
    quote: `Nellin observed the whirling movements of the Initates. "Are they practicing forms?" he asked. "No," came the instructor's reply. "They are meditating."`,
    set: 'CotG',
    text: 'Draw a card',
    title: 'Arha Initiate',
    type: 'hero'
  },
  {
    banishable: true,
    cost: 4,
    factions: ['enlightened'],
    honor: 3,
    id: 'arha_templar',
    quote: `Sharpen the mind, and the sword will follow.`,
    set: 'CotG',
    text: 'Defeat a Monster that has (4 power) or less without paying its cost.',
    title: 'Arha Templar',
    type: 'hero'
  },
  {
    banishable: true,
    cost: 5,
    factions: ['enlightened'],
    honor: 2,
    id: 'ascetic_of_the_lidless_eye',
    quote: `"There is nothing obscure about what is to come, Godslayer, the future is always clear to those who choose to see. It is your judgement that is clouded."`,
    set: 'CotG',
    text: 'Draw two cards.',
    title: 'Ascetic of the Lidless Eye',
    type: 'hero'
  },
  {
    banishable: true,
    cost: 4,
    factions: ['mechana'],
    honor: 2,
    id: 'avatar_golem',
    quote: ``,
    set: 'CotG',
    text: 'Gain (2 Power). Gain (1 Honor) for each faction among Constructs you control. (Factions are Enlightened, Mechana, Lifebound, and Void.)',
    title: 'Avatar Golem',
    type: 'hero'
  },
  {
    banishable: false,
    cost: 7,
    factions: ['monster'],
    honor: 4,
    id: 'avatar_of_the_fallen',
    quote: ``,
    set: 'CotG',
    text: 'Unbanishable. Reward: Gain (4 Honor). You may acquire or defeat any card in the center row without paying its cost.',
    title: 'Avatar of the Fallen',
    type: 'monster'
  },
  {
    banishable: true,
    cost: 3,
    factions: ['mechana'],
    honor: 2,
    id: 'burrower_mark_ii',
    quote: ``,
    set: 'CotG',
    text: 'Once per turn, when you put a Mechana Construct into play (including this one), draw a card.',
    title: 'Burrower Mark II',
    type: 'construct'
  },
  {
    banishable: true,
    cost: 7,
    factions: ['lifebound'],
    honor: 4,
    id: 'cetra_weaver_of_stars',
    quote: `"Your destiny is i the stars, and if the Mother finds you worthy, I will lay it at your feeet."`,
    set: 'CotG',
    text: 'Acquire a Hero without paying its cost. Place it on top of your deck.',
    title: 'Cetra, Weaver of Stars',
    type: 'hero'
  },
  {
    banishable: true,
    cost: 4,
    factions: ['monster'],
    honor: 3,
    id: 'corrosive_widow',
    quote: ``,
    set: 'CotG',
    text: 'Reward: Gain (3 Honor). Each opponent must destroy a Construct he controls.',
    title: 'Corrosive Widow',
    type: 'monster'
  },
  {
    banishable: true,
    cost: 4,
    factions: ['void'],
    honor: 2,
    id: 'demon_slayer',
    quote: `"How many demons have you slain stranger?" Sar asked, lowering his massive sword. "One so far," Nellin replied, and grinned. "But it was a really, really big one."`,
    set: 'CotG',
    text: 'Gain (3 Power).',
    title: 'Demon Slayer',
    type: 'hero'
  },
  {
    banishable: true,
    cost: 4,
    factions: ['lifebound'],
    honor: 3,
    id: 'druids_of_the_stone_circle',
    quote: `For countless centuries in Ogo the order of the Stone Circle worked to deepen their connection to all living things.`,
    set: 'CotG',
    text: 'Gain (3 Power).',
    title: 'Acquire a Hero with cost (3 Rune) or less without paying its cost. Place it on top of your deck.',
    type: 'hero'
  },
  {
    banishable: true,
    cost: 6,
    factions: ['monster'],
    honor: 5,
    id: 'earth_tyrant',
    quote: ``,
    set: 'CotG',
    text: 'Reward: Gain (5 Honor). Draw two cards.',
    title: 'Earth Tyrant',
    type: 'monster'
  },
  {
    banishable: true,
    cost: 5,
    factions: ['void'],
    honor: 2,
    id: 'flytrap_witch',
    quote: `She was guide to both would-be leaders, but only the Godslayer reached the other side of the swamp. His rival simply vanished.`,
    set: 'CotG',
    text: 'Gain (2 Honor). Draw a card.',
    title: 'Flytrap Witch',
    type: 'hero'
  },
  {
    banishable: true,
    cost: 8,
    factions: ['mechana'],
    honor: 8,
    id: 'hedron_cannon',
    quote: ``,
    set: 'CotG',
    text: 'Once per turn, gain (1 Power) for each Mechana Construct you control.',
    title: 'Hedron Cannon',
    type: 'construct'
  },
  {
    banishable: true,
    cost: 7,
    factions: ['mechana'],
    honor: 7,
    id: 'hedron_link_device',
    quote: ``,
    set: 'CotG',
    text: 'You may treat all Constructs as Mechana Constructs.',
    title: 'Hedron Link Device',
    type: 'construct'
  },
  {
    banishable: true,
    cost: 3,
    factions: ['mechana'],
    honor: 2,
    id: 'kor_the_ferromancer',
    quote: ``,
    set: 'CotG',
    text: 'Gain (2 Power). Draw a card if you control 2 or more Constructs.',
    title: 'Kor, the Ferromancer',
    type: 'hero'
  },
  {
    banishable: true,
    cost: 6,
    factions: ['lifebound'],
    honor: 3,
    id: 'landtalker',
    quote: ``,
    set: 'CotG',
    text: 'Gain (3 Rune).',
    title: 'Landtalker',
    type: 'hero'
  },
  {
    banishable: true,
    cost: 6,
    factions: ['lifebound'],
    honor: 3,
    id: 'lifebound_initiate',
    quote: ``,
    set: 'CotG',
    text: 'Gain (1 Rune) and (1 Honor).',
    title: 'Lifebound Initiate',
    type: 'hero'
  },
  {
    banishable: true,
    cost: 7,
    factions: ['enlightened'],
    honor: 3,
    id: 'master_dhartha',
    quote: ``,
    set: 'CotG',
    text: 'Draw three cards.',
    title: 'Master Dhartha',
    type: 'hero'
  },
  {
    banishable: true,
    cost: 1,
    factions: ['mechana'],
    honor: 1,
    id: 'mechana_initiate',
    quote: ``,
    set: 'CotG',
    text: 'Gain (1 Rune) or (1 Power).',
    title: 'Mechana Initiate',
    type: 'hero'
  },
  {
    banishable: true,
    cost: 3,
    factions: ['monster'],
    honor: 2,
    id: 'mephit',
    quote: ``,
    set: 'CotG',
    text: 'Reward: Gain (2 Honor). You may banish a card in the center row.',
    title: 'Mechana Initiate',
    type: 'monster'
  },
  {
    banishable: true,
    cost: 4,
    factions: ['monster'],
    honor: 4,
    id: 'mistake_of_creation',
    quote: ``,
    set: 'CotG',
    text: 'Reward: Gain (4 Honor). You may banish a card in the center row andor a card in your discard pile.',
    title: 'Mistake of Creation',
    type: 'monster'
  },
  {
    banishable: true,
    cost: 7,
    factions: ['void'],
    honor: 4,
    id: 'muramasa',
    quote: ``,
    set: 'CotG',
    text: 'Once per turn, Gain (3 Power).',
    title: 'Muramasa',
    type: 'construct'
  },
  {
    banishable: true,
    cost: 6,
    factions: ['enlightened'],
    honor: 3,
    id: 'oziah_the_peerless',
    quote: ``,
    set: 'CotG',
    text: 'Defeat a Monster that has (6 power) or less without paying its cost.',
    title: 'Oziah the Peerless',
    type: 'hero'
  },
  {
    banishable: true,
    cost: 4,
    factions: ['mechana'],
    honor: 2,
    id: 'reactor_monk',
    quote: ``,
    set: 'CotG',
    text: 'Gain (2 Rune). You pay (1 Rune) less the next time you acquire a Construct this turn.',
    title: 'Reactor Monk',
    type: 'hero'
  },
  {
    banishable: true,
    cost: 4,
    factions: ['mechana'],
    honor: 4,
    id: 'rocket_courier_x-99',
    quote: ``,
    set: 'CotG',
    text: 'Once per turn, when you acquire another Mechana Construct, you may put it directly into play.',
    title: 'Rocket Courier X-99',
    type: 'construct'
  },
  {
    banishable: true,
    cost: 3,
    factions: ['lifebound'],
    honor: 1,
    id: 'runic_lycanthrope',
    quote: ``,
    set: 'CotG',
    text: 'Gain (2 Rune). If you have played another Lifebound Hero this turn, gain (2 Power).',
    title: 'Runic Lycanthrope',
    type: 'construct'
  },
]
